#import "@local/xnotes:1.0.2": *
#show: doc => xnote(doc)
#set page(height: auto)

#title[Assignment 2][Xander Jhaveri]

= 1. Slab Space Saving

#align(center)[*Final Answer: 41.32 MB*]

#aside[I assumed that pages were 4096 bits or 512 bytes]

To calculate the space saved by using the slab allocator as opposed to
using a minimum of one page per object, we must calculate both the number of pages used by the slab allocator, and the number of pages that we would have used with normal paging.

To calculate the number of pages used by the slab allocator, we simply
multiply the number of objects by the size of each object, divide by the
page size, and round up. We then sum the corresponding values for every
object.

$
  "Pages Allocated with Slab Allocator" = sum ceil(("Object Size" dot "Number of Objects")/"Page Size")
$

To calculate the number of pages that would have been allocated when paging
per object, we multiply the number of objects by the number of pages
per object. We then sum the corresponding values for every object.

$
  "Pages Allocated with Per Object Paging" = sum ("Pages/Object" dot
    "Number of Objects")
$

#aside[Note: $"Pages/Object"$ could be calculated using $ceil("Object Size" / "Page Size")$. However, this value is also given in the slab info, `pagesperslab`, which is the value my awk scripts will use.]

We can then take the difference and multiply by the page size to find the total space saved:

$
  "Total Space Saved" = ("Pages w/ Per Object Paging" -
    "Pages w/ Slab Allocator") dot "Page Size"
$

#figure(caption: [q1.awk])[
  ```awk
  #!/usr/bin/awk -f

  # Number of Objects: $3
  # Object Size: $4
  # Pages per Slab: $6

  BEGIN {
    PAGE_SIZE = 512;
  }

  function ceil(x) {
      return (x == int(x)) ? x : int(x) + (x > 0 ? 1 : 0)
  }

  {
    current_slab_alloc_pages = ceil(($3 * $4) / PAGE_SIZE)
    current_perobj_pages = $6 * $3

    slab_alloc_pages += current_slab_alloc_pages
    perobj_pages += current_perobj_pages
  }

  END {
    pages_saved = perobj_pages - slab_alloc_pages
    space_saved = pages_saved * PAGE_SIZE

    printf("Pages used with Slab Allocator: %d\n", slab_alloc_pages)
    printf("Pages used with Per Object Paging: %d\n", perobj_pages)
    printf("Pages Saved with Slab Allocator: %d\n", pages_saved)
    printf("Page Size (in bytes): %d\n", PAGE_SIZE)
    printf("Space Saved (in bytes): %d\n", space_saved)
  }
  ```
]

After putting the given `slabinfo` into a file called `q1slabinfo.txt`, I
used the following command to compute the output: #box(outset: 3pt, fill: rgb("eeeeee"))[`awk -f q1.awk q1slabinfo.txt`]. Here is the output generated by the command:

#figure(caption: [Question 1. awk Script Output])[
  ```txt
  Pages used with Slab Allocator: 659862
  Pages used with Per Object Paging: 1466936
  Pages Saved with Slab Allocator: 807074
  Page Size (in bytes): 512
  Space Saved (in bytes): 413221888
  ```
]

The amount of space saved using slabs was *413221888 bytes*, or *41.32 MB*.

= 2. Buddy Algorithm in C
